name: DPE Daily Fetch

on:
  schedule:
    - cron: "15 6 * * *"   # tous les jours à 06h15 UTC (~8h15 Paris)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run fetch
        env:
          DPE_CSV_URL: ${{ secrets.DPE_CSV_URL }}
        run: python fetch_dpe_daily.py
      - name: Commit data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "chore(data): DPE $(date -u +'%Y-%m-%d')" || echo "rien à commit"
          git push
